In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('data\HR_emp.csv')
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [10]:
df.shape

(14999, 10)

In [14]:
df.rename(columns={'sales':'department'}, inplace=True)
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   department             14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [20]:
print(df.department.unique())
print(df.salary.unique())

['sales' 'accounting' 'hr' 'technical' 'support' 'management' 'IT'
 'product_mng' 'marketing' 'RandD']
['low' 'medium' 'high']


In [46]:
salry = pd.get_dummies(df['salary'])
salry

high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
...     ...  ...     ...
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
dept = le.fit_transform(df.department)

In [35]:
dept

array([7, 7, 7, ..., 8, 8, 8])

In [48]:
ohe = OneHotEncoder()
dept_ohe = ohe.fit_transform(dept.reshape(-1,1))
dept_ohe

<14999x10 sparse matrix of type '<class 'numpy.float64'>'
	with 14999 stored elements in Compressed Sparse Row format>

In [42]:
le.classes_

array(['IT', 'RandD', 'accounting', 'hr', 'management', 'marketing',
       'product_mng', 'sales', 'support', 'technical'], dtype=object)

In [50]:
###
df_dept = pd.DataFrame(dept_ohe.toarray(), dtype=int,columns=le.classes_)

In [51]:
df_dept

IT  RandD  accounting  hr  management  marketing  product_mng  sales  \
0       0      0           0   0           0          0            0      1   
1       0      0           0   0           0          0            0      1   
2       0      0           0   0           0          0            0      1   
3       0      0           0   0           0          0            0      1   
4       0      0           0   0           0          0            0      1   
...    ..    ...         ...  ..         ...        ...          ...    ...   
14994   0      0           0   0           0          0            0      0   
14995   0      0           0   0           0          0            0      0   
14996   0      0           0   0           0          0            0      0   
14997   0      0           0   0           0          0            0      0   
14998   0      0           0   0           0          0            0      0   

       support  technical  
0            0          0  
1            0          0  
2            0          0  
3            0          0  
4            0          0  
...        ...        ...  
14994        1          0  
14995        1          0  
14996        1          0  
14997        1          0  
14998        1          0  

[14999 rows x 10 columns]

In [52]:
salry

high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
...     ...  ...     ...
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [53]:
df['df_salry'] = df.salary.map({'low':1,'medium':2,'high':3})

In [54]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  df_salry  
0     low         1  
1  medium         2  
2  medium         2  
3     low         1  
4     low         1

In [56]:
df = df.drop(['department','salary'],axis=1)

In [57]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [58]:
df.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'df_salry'],
      dtype='object')

In [60]:
df_scale = df[['number_project', 'average_montly_hours','time_spend_company']]

In [61]:
mm = MinMaxScaler()

In [63]:
###
df_scaled = mm.fit_transform(df_scale)

array([[0.        , 0.28504673, 0.125     ],
       [0.6       , 0.77570093, 0.5       ],
       [1.        , 0.82242991, 0.25      ],
       ...,
       [0.        , 0.21962617, 0.125     ],
       [0.8       , 0.85981308, 0.25      ],
       [0.        , 0.28971963, 0.125     ]])

In [64]:
df_deptnp = df_dept.values

In [68]:
df_emp = df[['satisfaction_level', 'last_evaluation','Work_accident','promotion_last_5years', 'df_salry']]
df_empnp = df_emp.values

In [66]:
df_deptnp.shape

(14999, 10)

In [67]:
df_scaled.shape

(14999, 3)

In [70]:
df_empnp.shape

(14999, 5)

In [81]:
X = np.hstack([df_empnp,df_scaled,df_deptnp])

In [84]:
y = df.left

In [82]:
X.shape

(14999, 18)

In [85]:
y.value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [97]:
from sklearn.linear_model import LogisticRegression

In [98]:
lr = LogisticRegression(max_iter=100)

In [99]:
lr.fit(X_train,y_train)

LogisticRegression()

In [100]:
lr.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [101]:
lr.score(X_test,y_test)

0.7986666666666666

In [102]:
from sklearn.ensemble import RandomForestClassifier

In [104]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9890666666666666